version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2026.08.1
    resource_class: large
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3g
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "kobaia/build.gradle" }}-{{ checksum "sample/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "kobaia/build.gradle" }}-{{ checksum "sample/build.gradle" }}
      - run:
          name: Build library and sample app
          command: ./gradlew build
