plugins {
    id 'com.android.library'
}

android {
    namespace 'com.araujo.jordan.kobaia'
    compileSdk 37

    defaultConfig {
        minSdk 23
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        disable 'InvalidPackage'
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    api 'androidx.test:runner:1.7.0'
    api 'androidx.test:rules:1.7.0'
    api 'androidx.test.espresso:espresso-core:3.7.0'
    api 'androidx.test.uiautomator:uiautomator:2.4.0'
    api 'junit:junit:4.13.2'
    api 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'
}

// Exclude Kotlin files from Javadoc due to an error generating docs from Kotlin files.
// More info: https://github.com/novoda/bintray-release/issues/71
tasks.withType(Javadoc).configureEach {
    excludes = ['**/*.kt']
}
